include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

variables:
  WARNING1: "ignore::DeprecationWarning:orangecanvas.utils.localization"
  WARNING2: "ignore::DeprecationWarning:orangecanvas.utils.localization.si"
  IGNORE_WARNINGS: "-W ${WARNING1} -W ${WARNING2}"

flake8_nb:
  extends: .flake8_nb

isort:
  extends: .isort

test-3.8_glx:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - src/**/*
        - pyproject.toml
  extends: .test-3.8_glx
  timeout: 30m
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"
    QT_API: "PyQt6"

test-3.12-win:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - src/**/*
        - pyproject.toml
  extends: .test-3.12-win
  timeout: 30m
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"
    QT_API: "PyQt6"

build_sdist:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "1.1"
  extends: .build_sdist

test_sdist-3.8_glx:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "1.1"
  extends: .test_sdist-3.8_glx
  timeout: 30m
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"
    QT_API: "PyQt6"

test_sdist-3.12-win:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "1.1"
  extends: .test_sdist-3.12-win
  timeout: 15m
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: "-W error ${IGNORE_WARNINGS}"
    QT_API: "PyQt6"

build_doc:
  image: gitlab-registry.esrf.fr/dau/ci/pyci/python_3.12_glx:latest
  extends: .build_doc
  before_script:
    - apt-get install -y pandoc
    - !reference [.build_doc, before_script]
  variables:
    QT_API: "PyQt6"

pages:
  extends: .pages

assets:
  extends: .assets

release_testpypi:
  extends: .testpypi

release_pypi:
  extends: .pypi
